=== nextcloud/appstore/nextcloudappstore/core/api/v1/release/info.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="id" minOccurs="1" maxOccurs="1"/>
                <xs:element name="name" type="l10n-string" minOccurs="1"
                            maxOccurs="unbounded"/>
                <xs:element name="summary" type="l10n-string" minOccurs="1"
                            maxOccurs="unbounded"/>
                <xs:element name="description" type="l10n-text" minOccurs="1"
                            maxOccurs="unbounded"/>
                <xs:element name="version" type="version"
                            minOccurs="1" maxOccurs="1"/>
                <xs:element name="licence" type="licence" minOccurs="1"
                            maxOccurs="1"/>
                <xs:element name="author" type="author" minOccurs="1"
                            maxOccurs="unbounded"/>
                <xs:element name="namespace" type="limited-string"
                            minOccurs="0" maxOccurs="1"/>
                <xs:element name="types" type="types" minOccurs="0"
                            maxOccurs="1"/>
                <xs:element name="documentation" type="documentation"
                            minOccurs="0" maxOccurs="1"/>
                <xs:element name="category" type="category" minOccurs="1"
                            maxOccurs="unbounded"/>
                <xs:element name="website" type="url" minOccurs="0"
                            maxOccurs="1"/>
                <xs:element name="bugs" type="url" minOccurs="0"
                            maxOccurs="1"/>
                <xs:element name="repository" type="repository" minOccurs="0"
                            maxOccurs="1"/>
                <xs:element name="discussion" type="discussion-url" minOccurs="0"
                            maxOccurs="1"/>
                <xs:element name="screenshot" type="secure-url" minOccurs="0"
                            maxOccurs="10"/>
                <xs:element name="dependencies" type="dependencies"
                            minOccurs="1" maxOccurs="1"/>
                <xs:element name="background-jobs" type="jobs"
                            minOccurs="0" maxOccurs="1"/>
                <xs:element name="repair-steps" type="repair-steps"
                            minOccurs="0" maxOccurs="1"/>
                <xs:element name="two-factor-providers" type="two-factor-providers"
                            minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueNameL10n">
            <xs:selector xpath="name"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
        <xs:unique name="uniqueSummaryL10n">
            <xs:selector xpath="summary"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
        <xs:unique name="uniqueDescriptionL10n">
            <xs:selector xpath="description"/>
            <xs:field xpath="@lang"/>
        </xs:unique>
        <xs:unique name="uniqueLicense">
            <xs:selector xpath="licence"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="uniqueTypes">
            <xs:selector xpath="types/type"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="uniqueCategory">
            <xs:selector xpath="category"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="uniqueDatabase">
            <xs:selector xpath="dependencies/database"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="uniqueLib">
            <xs:selector xpath="dependencies/lib"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="uniqueCommand">
            <xs:selector xpath="dependencies/command"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>

    <!-- basic types -->
    <xs:simpleType name="empty-string">
        <xs:restriction base="xs:string">
            <xs:maxLength value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="non-empty-string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="limited-string">
        <xs:restriction base="non-empty-string">
            <xs:maxLength value="128"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="l10n-text">
        <xs:simpleContent>
            <xs:extension base="non-empty-string">
                <xs:attribute name="lang" type="l10n-code" default="en"
                              use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="l10n-string">
        <xs:simpleContent>
            <xs:restriction base="l10n-text">
                <xs:maxLength value="128"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>


    <xs:simpleType name="l10n-code">
        <xs:restriction base="xs:string">
            <xs:enumeration value="af"/>
            <xs:enumeration value="ar"/>
            <xs:enumeration value="ast"/>
            <xs:enumeration value="az"/>
            <xs:enumeration value="bg"/>
            <xs:enumeration value="be"/>
            <xs:enumeration value="bn"/>
            <xs:enumeration value="br"/>
            <xs:enumeration value="bs"/>
            <xs:enumeration value="ca"/>
            <xs:enumeration value="cs"/>
            <xs:enumeration value="cy"/>
            <xs:enumeration value="da"/>
            <xs:enumeration value="de"/>
            <xs:enumeration value="el"/>
            <xs:enumeration value="en"/>
            <xs:enumeration value="en-au"/>
            <xs:enumeration value="en-gb"/>
            <xs:enumeration value="eo"/>
            <xs:enumeration value="es"/>
            <xs:enumeration value="es-ar"/>
            <xs:enumeration value="es-co"/>
            <xs:enumeration value="es-mx"/>
            <xs:enumeration value="es-ni"/>
            <xs:enumeration value="es-ve"/>
            <xs:enumeration value="et"/>
            <xs:enumeration value="eu"/>
            <xs:enumeration value="fa"/>
            <xs:enumeration value="fi"/>
            <xs:enumeration value="fr"/>
            <xs:enumeration value="fy"/>
            <xs:enumeration value="ga"/>
            <xs:enumeration value="gd"/>
            <xs:enumeration value="gl"/>
            <xs:enumeration value="he"/>
            <xs:enumeration value="hi"/>
            <xs:enumeration value="hr"/>
            <xs:enumeration value="hu"/>
            <xs:enumeration value="ia"/>
            <xs:enumeration value="id"/>
            <xs:enumeration value="io"/>
            <xs:enumeration value="is"/>
            <xs:enumeration value="it"/>
            <xs:enumeration value="ja"/>
            <xs:enumeration value="ka"/>
            <xs:enumeration value="kk"/>
            <xs:enumeration value="km"/>
            <xs:enumeration value="kn"/>
            <xs:enumeration value="ko"/>
            <xs:enumeration value="lb"/>
            <xs:enumeration value="lt"/>
            <xs:enumeration value="lv"/>
            <xs:enumeration value="mk"/>
            <xs:enumeration value="ml"/>
            <xs:enumeration value="mn"/>
            <xs:enumeration value="mr"/>
            <xs:enumeration value="my"/>
            <xs:enumeration value="nb"/>
            <xs:enumeration value="ne"/>
            <xs:enumeration value="nl"/>
            <xs:enumeration value="nn"/>
            <xs:enumeration value="os"/>
            <xs:enumeration value="pa"/>
            <xs:enumeration value="pl"/>
            <xs:enumeration value="pt"/>
            <xs:enumeration value="pt-br"/>
            <xs:enumeration value="ro"/>
            <xs:enumeration value="ru"/>
            <xs:enumeration value="sk"/>
            <xs:enumeration value="sl"/>
            <xs:enumeration value="sq"/>
            <xs:enumeration value="sr"/>
            <xs:enumeration value="sr-latn"/>
            <xs:enumeration value="sv"/>
            <xs:enumeration value="sw"/>
            <xs:enumeration value="ta"/>
            <xs:enumeration value="te"/>
            <xs:enumeration value="th"/>
            <xs:enumeration value="tr"/>
            <xs:enumeration value="tt"/>
            <xs:enumeration value="udm"/>
            <xs:enumeration value="uk"/>
            <xs:enumeration value="ur"/>
            <xs:enumeration value="vi"/>
            <xs:enumeration value="zh-hans"/>
            <xs:enumeration value="zh-hant"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="version">
        <xs:restriction base="limited-string">
            <xs:pattern value="[0-9]+(\.[0-9]+){0,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="url">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.+"/>
            <xs:maxLength value="256"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="secure-url">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://.+"/>
            <xs:maxLength value="256"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- for now only allow urls to our forum -->
    <xs:simpleType name="discussion-url">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://help\.nextcloud\.com.*/\d+"/>
            <xs:maxLength value="256"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="email">
        <xs:restriction base="limited-string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- first level elements -->
    <xs:simpleType name="id">
        <xs:restriction base="limited-string">
            <xs:pattern value="[a-z]+[a-z_]*[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="author">
        <xs:simpleContent>
            <xs:extension base="limited-string">
                <xs:attribute name="mail" type="email" use="optional"/>
                <xs:attribute name="homepage" type="url" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="repository">
        <xs:simpleContent>
            <xs:extension base="url">
                <xs:attribute name="type" type="vcs" use="optional"
                              default="git"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="vcs">
        <xs:restriction base="xs:string">
            <xs:enumeration value="git"/>
            <xs:enumeration value="mercurial"/>
            <xs:enumeration value="subversion"/>
            <xs:enumeration value="bzr"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="types">
        <xs:sequence>
            <xs:element name="prelogin" minOccurs="0" maxOccurs="1"/>
            <xs:element name="filesystem" minOccurs="0" maxOccurs="1"/>
            <xs:element name="authentication" minOccurs="0" maxOccurs="1"/>
            <xs:element name="logging" minOccurs="0" maxOccurs="1"/>
            <xs:element name="prevent_group_restriction" minOccurs="0"
                        maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="category">
        <xs:restriction base="xs:string">
            <xs:enumeration value="customization"/>
            <xs:enumeration value="files"/>
            <xs:enumeration value="integration"/>
            <xs:enumeration value="monitoring"/>
            <xs:enumeration value="multimedia"/>
            <xs:enumeration value="office"/>
            <xs:enumeration value="organization"/>
            <xs:enumeration value="social"/>
            <xs:enumeration value="tools"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="licence">
        <xs:restriction base="xs:string">
            <xs:enumeration value="agpl"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="databases">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sqlite"/>
            <xs:enumeration value="mysql"/>
            <xs:enumeration value="pgsql"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="documentation">
        <xs:sequence>
            <xs:element name="user" type="url" minOccurs="0" maxOccurs="1"/>
            <xs:element name="admin" type="url" minOccurs="0" maxOccurs="1"/>
            <xs:element name="developer" type="url" minOccurs="0"
                        maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <!-- dependencies -->
    <xs:complexType name="dependencies">
        <xs:sequence>
            <xs:element name="php" type="php" minOccurs="0" maxOccurs="1"/>
            <xs:element name="database" type="database" minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="command" type="limited-string" minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="lib" type="min-max-version" minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="owncloud" type="nextcloud" minOccurs="1"
                        maxOccurs="1"/>
            <xs:element name="nextcloud" type="nextcloud" minOccurs="1"
                        maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nextcloud">
        <xs:attribute name="min-version" type="version" use="required"/>
        <xs:attribute name="max-version" type="version" use="optional"/>
    </xs:complexType>

    <xs:complexType name="min-max-version">
        <xs:simpleContent>
            <xs:extension base="limited-string">
                <xs:attribute name="min-version" type="version"
                              use="optional"/>
                <xs:attribute name="max-version" type="version"
                              use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:simpleContent>
            <xs:extension base="databases">
                <xs:attribute name="min-version" type="version"
                              use="optional"/>
                <xs:attribute name="max-version" type="version"
                              use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="php">
        <xs:simpleContent>
            <xs:extension base="empty-string">
                <xs:attribute name="min-int-size" type="bits" use="optional"
                              default="32"/>
                <xs:attribute name="min-version" type="version"
                              use="optional"/>
                <xs:attribute name="max-version" type="version"
                              use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="bits">
        <xs:restriction base="xs:int">
            <xs:enumeration value="32"/>
            <xs:enumeration value="64"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="repair-steps">
        <xs:sequence>
            <xs:element name="pre-migration" type="steps" minOccurs="0"
                        maxOccurs="1"/>
            <xs:element name="post-migration" type="steps" minOccurs="0"
                        maxOccurs="1"/>
            <xs:element name="live-migration" type="steps" minOccurs="0"
                        maxOccurs="1"/>
            <xs:element name="install" type="steps" minOccurs="0"
                        maxOccurs="1"/>
            <xs:element name="uninstall" type="steps" minOccurs="0"
                        maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jobs">
        <xs:sequence>
            <xs:element name="job" type="php-class" minOccurs="1"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="steps">
        <xs:sequence>
            <xs:element name="step" type="php-class" minOccurs="1"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="two-factor-providers">
        <xs:sequence>
            <xs:element name="provider" type="php-class" minOccurs="1"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="php-class">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_][0-9a-zA-Z_]*(\\[a-zA-Z_][0-9a-zA-Z_]*)*"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== nextcloud/appstore/nextcloudappstore/scaffolding/app-templates/25/app/appinfo/info.xml
<?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
    <!--
    SPDX-FileCopyrightText: {{ app.author_name }} <{{ app.author_mail }}>
    SPDX-License-Identifier: CC0-1.0
    -->
    <id>{{ app.id }}</id>
    <name>{{ app.name }}</name>
    <summary>{{ app.summary }}</summary>
    <description><![CDATA[{{ app.description }}]]></description>
    <version>0.0.1</version>
    <licence>agpl</licence>
    <author {% if app.author_mail %}mail="{{ app.author_mail }}"{% endif %} {% if app.author_homepage %}homepage="{{ app.author_homepage }}"{% endif %}>{{ app.author_name }}</author>
    <namespace>{{ app.namespace }}</namespace>{% for category in app.categories %}
    <category>{{ category }}</category>{% endfor %}
    <bugs>{{ app.issue_tracker }}</bugs>
    <dependencies>
        <nextcloud min-version="{{ app.nextcloud_version }}" max-version="{{ app.nextcloud_version }}"/>
    </dependencies>
    <navigations>
        <navigation>
            <name>{{ app.name }}</name>
            <route>{{ app.id }}.page.index</route>
        </navigation>
    </navigations>
</info>

=== nextcloud/appstore/nextcloudappstore/api/v1/tests/data/infoxmls/digits.xml
<?xml version="1.0"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../release/info.xsd">
    <id>twofactor_u2f</id>
    <name>News</name>
    <description>An RSS/Atom feed reader</description>
    <version>8.8.2</version>
    <licence>agpl</licence>
    <author>Bernhard Posselt</author>
    <category>multimedia</category>
    <bugs>https://github.com/nextcloud/news/issues</bugs>
    <dependencies>
        <owncloud min-version="9.0" max-version="9.0"/>
    </dependencies>
</info>

=== nextcloud/appstore/nextcloudappstore/core/scaffolding/app-templates/10/app/appinfo/info.xml
<?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
    <id>{{ app.id }}</id>
    <name>{{ app.name }}</name>
    <summary>{{ app.summary }}</summary>
    <description><![CDATA[{{ app.description }}]]></description>
    <licence>agpl</licence>
    <author {% if app.author_mail %}mail="{{ app.author_mail }}"{% endif %} {% if app.author_homepage %}homepage="{{ app.author_homepage }}"{% endif %}>{{ app.author_name }}</author>
    <version>0.0.1</version>
    <namespace>{{ app.namespace }}</namespace>{% for category in app.categories %}
    <category>{{ category }}</category>{% endfor %}
    <dependencies>
        <owncloud min-version="{{ app.nextcloud_version }}"/>
        <nextcloud min-version="{{ app.owncloud_version }}"/>
    </dependencies>
</info>

=== nextcloud/appstore/nextcloudappstore/core/api/v1/tests/data/infoxmls/transform.xml
<?xml version="1.0"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../release/info.xsd">
    <id>news</id>
    <name>News</name>
    <summary>An RSS/Atom feed reader</summary>
    <description>An RSS/Atom feed reader</description>
    <version>8.8.2</version>
    <licence>agpl</licence>
    <author>Bernhard Posselt</author>
    <category>multimedia</category>
    <dependencies>
        <owncloud min-version="9.1" max-version="9.2"/>
    </dependencies>
</info>

=== nextcloud/appstore/nextcloudappstore/scaffolding/tests/data/info.xml
<?xml version="1.0"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
	<id>theapp</id>
	<name>The App</name>
	<summary>a summary</summary>
	<description>a description</description>
	<version>1.0.0</version>
	<licence>AGPL-3.0-or-later</licence>
	<author mail="author email" homepage="author homepage">author name</author>
	<namespace>TheApp</namespace>
	<category>tools</category>
	<bugs>https://test.com</bugs>
	<dependencies>
		<nextcloud min-version="31" max-version="33"/>
	</dependencies>
	<navigations>
		<navigation>
			<id>theapp</id>
			<name>The App</name>
			<route>theapp.page.index</route>
			<icon>app.svg</icon>
			<type>link</type>
		</navigation>
	</navigations>
</info>

=== nextcloud/appstore/nextcloudappstore/core/api/v1/tests/data/infoxmls/repair-and-jobs.xml
<?xml version="1.0"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../appmetadata/info.xsd">
    <id>news</id>
    <name>News</name>
    <summary>An RSS/Atom feed reader</summary>
    <description>An RSS/Atom feed reader</description>
    <version>8.8.2</version>
    <licence>agpl</licence>
    <author>Bernhard Posselt</author>
    <category>multimedia</category>
    <dependencies>
        <owncloud min-version="9.0"/>
    </dependencies>
    <background-jobs>
        <job>OCA\DAV\CardDAV\Sync\SyncJob</job>
    </background-jobs>
    <repair-steps>
        <live-migration>
            <step>OCA\DAV\Migration\GenerateBirthdays</step>
        </live-migration>
        <post-migration>
            <step>OCA\DAV\Migration\Classification</step>
        </post-migration>
    </repair-steps>
    <two-factor-providers>
        <two-factor-provider>OCA\Hi</two-factor-provider>
    </two-factor-providers>
</info>
